### ISSUE TITLE
Broken on Ruby 2.2.4 and higher

### ISSUE THREAD

**Issue by Parmandil** [supremebeing7/time_log_robot#38] opened 2016-09-12 17:03 UTC
When Ruby 2.2.4 or higher is installed, I get an error that seems to be coming from the commander gem. It looks like this:

```
/Users/melanie/.gem/ruby/2.2.4/gems/commander-4.4.0/lib/commander/runner.rb:407:in `block in require_program': program version required (Commander::Runner::CommandError)
from /Users/melanie/.gem/ruby/2.2.4/gems/commander-4.4.0/lib/commander/runner.rb:406:in `each'
from /Users/melanie/.gem/ruby/2.2.4/gems/commander-4.4.0/lib/commander/runner.rb:406:in `require_program'
from /Users/melanie/.gem/ruby/2.2.4/gems/commander-4.4.0/lib/commander/runner.rb:52:in `run!'
from /Users/melanie/.gem/ruby/2.2.4/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
from /Users/melanie/.gem/ruby/2.2.4/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'
/Users/melanie/.rubies/ruby-2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:114:in `require': unable to find a version of 'activesupport' to activate (Gem::LoadError)
from /Users/melanie/.gem/ruby/2.2.4/gems/time_log_robot-0.2.1/lib/time_log_robot/toggl/report.rb:1:in `<top (required)>'
from /Users/melanie/.rubies/ruby-2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
from /Users/melanie/.rubies/ruby-2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
from /Users/melanie/.gem/ruby/2.2.4/gems/time_log_robot-0.2.1/bin/time_log_robot:10:in `<top (required)>'
from /Users/melanie/.gem/ruby/2.2.4/bin/time_log_robot:23:in `load'
from /Users/melanie/.gem/ruby/2.2.4/bin/time_log_robot:23:in `<main>' 
```

Reverting to an older Ruby solves the error.

**Comment by supremebeing7** [comment] 2016-09-12 18:16
Hm, I just checked and have been on 2.2.4 for awhile, with no issues. So, I suspect this is some kind of version issue with commander. If you have any steps or suggestions for how to reproduce this, please let me know.

**Comment by supremebeing7** [comment] 2016-09-12 18:22
Sounds like this may actually be JSON related again...  See: https://github.com/jekyll/jekyll/issues/1727

It may be we just need to lock commander at a certain version. Or it may be worthwhile to try a larger refactor to remove commander entirely since there really isn't a lot of command line stuff.

**Comment by supremebeing7** [comment] 2016-09-12 18:32
Actually, reading that thread further, locking commander version I don't think is the solution. It sounds like the issue occurs when the commander executable runs with a bad JSON version:

> Commander throws that program version required error whenever there is a problem loading in the executable (in this case, bin/jekyll). As 1.8.7 can't load an internal json library (introduced in 1.9), you'll need to install the gem.

Seems related: https://github.com/supremebeing7/time_log_robot/issues/37

I think this confirms we need to lock JSON at 1.8.1. I'll push that update, then you'll probably need to uninstall json 1.8.3 and either `gem update time_log_robot` or `gem uninstall time_log_robot && gem install time_log_robot` and see if that does the trick.

**Comment by supremebeing7** [comment] 2016-09-12 18:59
New version pushed, so make sure you're using time_log_robot 0.2.2 which has json locked at 1.8.1.

**Comment by Parmandil** [comment] 2016-10-10 17:56
Getting this error on a new computer with a new setup.

**Comment by supremebeing7** [comment] 2017-02-13 22:36
Just encountered this issue with someone else. The solution seems to be uninstall json 1.8.3 and `gem update time_log_robot`. This is some kind of bug with one of the dependencies that I have no control over other than to not use that dependency - which is the goal of https://github.com/supremebeing7/time_log_robot/issues/40.

Closing this one.

**Closed as completed by supremebeing7** 2017-02-13 22:36 UTC
Labels: bug, HIGH priority
